### ISSUE TITLE
patchData['path'] not working?

### ISSUE THREAD

**Issue by danklassen** [mlocati/composer-patcher#10]
I'm not sure if I'm doing something incorrect with my setup but I am getting an Exception: "The value of a patch must be a string or an array with a 'path' node value"

Should the last `\is_string($patchData['path'])` actually be negated like: `!\is_string($patchData['path'])`

https://github.com/mlocati/composer-patcher/blob/d8a70dc1086fc1b16b54ec42c664f7929b13e647/src/PatchCollector.php#L193

A sample of a section that is failing for me in my composer.json:
```
"patches": {
  "concrete5/core:9.0.2": {
    "Top Navigation Set Active States": {
      "path": "patches/concrete5/core/9.0.2-top-nav-set-active-state.patch",
      "levels": ["-p2"]
    }
  }
}
```

By the way, thanks for creating and releasing this very helpful package!

**Comment by mlocati** [comment]
Nice catch, thanks for the report!
